# This is a config for E2B sandbox template.
# You can use template ID (nssc60krygj18tuz9ut4) or template name (tespsets2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("tespsets2") # Sync sandbox
# sandbox = await AsyncSandbox.create("tespsets2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('tespsets2')

team_id = "0335664b-bcaf-49d8-9f98-41104e7c054e"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "tespsets2"
template_id = "nssc60krygj18tuz9ut4"
